#
# Module manifest for module 'powershell-zip'
#
# Generated by: Juliano Sales
#
# Generated on: 25-10-2015

@{
    Author = "Juliano Sales"
    ModuleVersion = "0.0.0"
    HelpInfoUri = "https://github.com/julianosaless/powershellzip"
    FunctionsToExport = @( 'Zip','Unzip')
}


function Zip {
    [CmdletBinding()]
    Param($source,$destination)
    Dowload -pathProgram (Join-path $env:temp 7z)
    
    set-alias sz "$env:temp\7z\7za.exe"
    sz a -tzip "$destination" "$source"
}

function Unzip {
  [CmdletBinding()]
  param($source, $destination)

  [Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem");
  [System.IO.Compression.ZipFile]::ExtractToDirectory($source, $destination)
}

function Dowload {
    [CmdletBinding()]
    Param($pathProgram)

    if (-not (test-path "$Env:temp\7z")){
		$pathDowload = Join-path $env:temp 7z.zip
		$url = "http://www.7-zip.org/a/7za920.zip"
		Invoke-WebRequest $url -OutFile $pathDowload
        Unzip $pathDowload $pathProgram
	}
}
