#
# Module manifest for module 'powershell-zip'
#
# Generated by: Juliano Sales
#
# Generated on: 25-10-2015

@{
    Author = "Juliano Sales"
    ModuleVersion = "0.0.0"
    HelpInfoUri = "https://github.com/julianosaless/powershellzip"
    FunctionsToExport = @( 'Zip', 'UnZip')
}

function Zip  {
    [CmdletBinding()]
    Param($source,$destination)
    
    $pathProgram = Join-path $env:temp 7z
    Dowload -pathProgram $pathProgram
    
    set-alias sz "$pathProgram\7za.exe"
    sz a -tzip "$destination" "$source\*"
}

function UnZip {
    [CmdletBinding()]
    Param($source, $destination)
    [System.IO.Compression.ZipFile]::ExtractToDirectory($source, $destination)
}

function Dowload {
    [CmdletBinding()]
    Param($pathProgram)
   
    if (-not (test-path "$Env:temp\7z")){
		$pathDowload = Join-path $env:temp 7z.zip
		$url = "http://www.7-zip.org/a/7za920.zip"
		Invoke-WebRequest $url -OutFile $pathDowload
        UnZip  $pathDowload  $pathProgram
	}
}
